name: DATE

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: View the date
        run: date